layout_spectrum: 0.28880809768222937
typography_spectrum: 0.6019369773396134
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.3935149319152726
  lightness: 0.6689457045922443
  saturation: 0.3665426718821694
  rhythmicContrast: 0.27480769274498124
name: Analytics Tao
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Buzz me
    url: 'mailto:bizolink@gmail.com'
title: Analytics Tao
description: Tao of Analytics + Rants
author:
  name: Kenneth Goh
  email: bcgoh.net@gmail.com
  url: 'http://www.analyticstao.com/'
content_rating:
  adult: false
navigation:
  - name: About
    id: f9a3ed14-6f1b-4b8c-865b-7a4eac7593c2
    type: content
content: []
github: true
url: 'http://analyticstao.com/'
