typography_spectrum: 0.4932751584231927
content_rating:
  adult: false
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.10774453152063312
  lightness: 0.013569808445114753
  saturation: 0.6892218571001351
  rhythmicContrast: 0.21531536298527354
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.6226712567282675
analytics:
  google: UA-97334757-1
author:
  name: Kenneth Goh
  email: bcgoh.net@gmail.com
  url: 'http://www.analyticstao.com/'
name: Analytics Tao
url: 'http://analyticstao.com/'
navigation:
  - name: About Me
    id: 98d943c2-5baa-45bc-a29e-2ff90279069f
    type: content
  - name: Useful Links
    id: fd10fc3c-ad12-4eb5-a777-b0fed74c0394
    type: content
title: Analytics Tao
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fj-0cUmUyb-Y%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dj-0cUmUyb-Y&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fj-0cUmUyb-Y%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=j-0cUmUyb-Y'
      keywords:
        - \tim smith\
        - cern
        - tedx
        - tedxcern
        - \ted
        - ed\
        - tededucation
        - ted-ed
        - \big
        - data\
        - \cern
        - big
        - data
      related: []
      author:
        - name: TED-Ed
          url: 'https://www.youtube.com/user/TEDEducation'
          avatar: {}
      '@context': 'http://schema.org'
      title: Big Data - Tim Smith
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=j-0cUmUyb-Y'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=j-0cUmUyb-Y
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=j-0cUmUyb-Y
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      description: >-
        View full lesson:
        http://ed.ted.com/lessons/exploration-on-the-big-data-frontier-tim-smith
        There is a mind-boggling amount of data floating around our society.
        Physicists at CERN have been pondering how to store and share their ever
        more massive data for decades - stimulating globalization of the
        internet along the way, whilst 'solving' their big data problem.
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Tao of Analytics + Rants
purpose:
  - type: contact
    label: Buzz me
    url: 'mailto:bizolink@gmail.com'
