layout_spectrum: 0.2338442796460436
typography_spectrum: 0.38387001934341425
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.4666343898548385
  lightness: 0.2827984978704907
  saturation: 0.049142348540504234
  rhythmicContrast: 0.37632199459700005
name: Analytics Tao
analytics:
  google: UA-97334757-1
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Contact me
    url: 'mailto:bizolink@gmail.com'
title: Analytics Tao
description: Tao of Analytics + Rants
author:
  name: Kenneth Goh
  url: 'http://www.analyticstao.com/'
  email: bizolink@gmail.com
content_rating:
  adult: false
navigation:
  - name: About Me
    id: 98d943c2-5baa-45bc-a29e-2ff90279069f
    type: content
  - name: Useful Links
    id: fd10fc3c-ad12-4eb5-a777-b0fed74c0394
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FeVSfJhssXUA%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DeVSfJhssXUA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FeVSfJhssXUA%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: World Economic Forum
          url: 'https://www.youtube.com/user/WorldEconomicForum'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      description: 'http://www.weforum.org/'
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=eVSfJhssXUA'
      title: What is big data?
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
