layout_spectrum: 0.28880809768222937
typography_spectrum: 0.6019369773396134
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.3935149319152726
  lightness: 0.6689457045922443
  saturation: 0.3665426718821694
  rhythmicContrast: 0.27480769274498124
name: Analytics Tao
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Buzz me
    url: 'mailto:bizolink@gmail.com'
title: Analytics Tao
description: Tao of Analytics + Rants
author:
  name: Kenneth Goh
  email: bcgoh.net@gmail.com
  url: 'http://www.analyticstao.com/'
content_rating:
  adult: false
navigation:
  - name: About
    id: f9a3ed14-6f1b-4b8c-865b-7a4eac7593c2
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d603825b-960f-4005-9968-78718e1f524f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d603825b-960f-4005-9968-78718e1f524f.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0900d338-26d4-4edd-b801-c68b4e21b491.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0900d338-26d4-4edd-b801-c68b4e21b491.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
url: 'http://analyticstao.com/'
