layout_spectrum: 0.2338442796460436
typography_spectrum: 0.38387001934341425
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.4666343898548385
  lightness: 0.2827984978704907
  saturation: 0.049142348540504234
  rhythmicContrast: 0.37632199459700005
name: Analytics Tao
analytics:
  google: UA-97334757-1
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Buzz me
    url: 'mailto:bizolink@gmail.com'
  - type: external
    url: 'https://api.whatsapp.com/send?phone=60163653399&text=Hello'
    label: Whatsapp
title: Analytics Tao
description: Tao of Analytics + Rants
author:
  name: Kenneth Goh
  url: 'http://www.analyticstao.com/'
  email: bizolink@gmail.com
content_rating:
  adult: false
navigation:
  - name: About Me
    id: 98d943c2-5baa-45bc-a29e-2ff90279069f
    type: content
  - name: Useful Links
    id: fd10fc3c-ad12-4eb5-a777-b0fed74c0394
    type: content
content: []
github: true
