layout_spectrum: 0.28880809768222937
typography_spectrum: 0.6019369773396134
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.3935149319152726
  lightness: 0.6689457045922443
  saturation: 0.3665426718821694
  rhythmicContrast: 0.27480769274498124
name: Analytics Tao
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Buzz me
    url: 'mailto:bizolink@gmail.com'
title: Analytics Tao
description: Tao of Analytics + Rants
author:
  name: Kenneth Goh
  email: bcgoh.net@gmail.com
  url: 'http://www.analyticstao.com/'
content_rating:
  adult: false
navigation:
  - name: About
    id: f9a3ed14-6f1b-4b8c-865b-7a4eac7593c2
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fj-0cUmUyb-Y%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dj-0cUmUyb-Y&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fj-0cUmUyb-Y%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: TED-Ed
          url: 'https://www.youtube.com/user/TEDEducation'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - \tim smith\
        - cern
        - tedx
        - tedxcern
        - \ted
        - ed\
        - tededucation
        - ted-ed
        - \big
        - data\
        - \cern
        - big
        - data
      description: >-
        View full lesson:
        http://ed.ted.com/lessons/exploration-on-the-big-data-frontier-tim-smith
        There is a mind-boggling amount of data floating around our society.
        Physicists at CERN have been pondering how to store and share their ever
        more massive data for decades - stimulating globalization of the
        internet along the way, whilst 'solving' their big data problem.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=j-0cUmUyb-Y&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=j-0cUmUyb-Y'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=j-0cUmUyb-Y
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=j-0cUmUyb-Y
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=j-0cUmUyb-Y'
      title: Big Data - Tim Smith
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
url: 'http://analyticstao.com/'
