layout_spectrum: 0.7248217238803015
typography_spectrum: 0.517540396458497
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.17815529648288347
  lightness: 0.07841345638497779
  saturation: 0.9542414827050991
  rhythmicContrast: 0.8666413264929105
name: Analytics Tao
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Buzz me
    url: 'mailto:bizolink@gmail.com'
title: Analytics Tao
description: Tao of Analytics + Rants
author:
  name: Kenneth Goh
  email: bcgoh.net@gmail.com
  url: 'http://www.analyticstao.com/'
content_rating:
  adult: false
navigation:
  - name: About
    id: f9a3ed14-6f1b-4b8c-865b-7a4eac7593c2
    type: content
content: []
github: true
url: 'http://analyticstao.com/'
